version: 0.2

env:
  variables:
    LAMBDA_FUNCTION_NAME: "testlambda"
    AWS_DEFAULT_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies (if any)..."
      - npm install --production || true

  build:
    commands:
      - echo "Building Lambda package..."
      - mkdir output
      - cp -r *.js package*.json output/
      - cd output
      - zip -r ../function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Deploying Lambda code..."
      - aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://function.zip \
          --publish

      # Optional: Store unzipped files to S3 for visibility
      - echo "Uploading readable source to S3..."
      - aws s3 sync ./output s3://my-lambda-readable-code-bucket/testlambda/ --delete

      - echo "Lambda function updated successfully!"

artifacts:
  files:
    - '**/*.js'
    - 'package.json'
    - 'function.zip'
  discard-paths: no
