version: 0.2

env:
  variables:
    LAMBDA_FUNCTION_NAME: "job_campaign_worker"
    AWS_DEFAULT_REGION: "ap-southeast-2"
    S3_BUCKET: "triggerlambda0312255"
    S3_KEY: "lambda/function.zip"

phases:
  install:
    commands:
      - echo "Nothing to install"

  build:
    commands:
      - mkdir package
      - cp -R * package
      - cd package
      - zip -r ../function.zip .

  post_build:
    commands:
      - aws s3 cp function.zip s3://$S3_BUCKET/$S3_KEY
      - aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --s3-bucket $S3_BUCKET \
          --s3-key $S3_KEY \
          --publish

artifacts:
  files:
    - function.zip
