version: 0.2

env:
  variables:
    LAMBDA_FUNCTION_NAME: "testlambda"
    AWS_DEFAULT_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies (if any)..."
      - npm install --production || true

  build:
    commands:
      - echo "Zipping Lambda code..."
      - mkdir -p output
      - cp -r *.js package*.json output/
      - cd output
      - zip -r function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Checking files before deploy..."
      - ls -lh output/
      - echo "Deploying Lambda code..."
      - aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://output/function.zip \
          --publish
      - echo "Lambda function updated successfully!"

artifacts:
  files:
    - 'output/function.zip'
  discard-paths: yes

