version: 0.2
env:
  variables:
    LAMBDA_FUNCTION_NAME: "testlambda"
    AWS_DEFAULT_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install --production || true

  build:
    commands:
      - echo "Build started..."
      - mkdir -p output
      - echo "Creating Lambda deployment package..."
      - zip -r output/function.zip . -x "buildspec*" "*.git*" "*.md" "node_modules/.cache/*"

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Verifying ZIP contents..."
      - unzip -l output/function.zip   # <-- This lists the files in the ZIP
      - echo "Updating Lambda function directly..."
      - aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://output/function.zip \
          --publish \
          --region $AWS_DEFAULT_REGION
      - echo "✅ Lambda function code updated successfully!"

artifacts:
  files:
    - 'output/function.zip'
  discard-paths: yes
