version: 0.2

env:
  variables:
    LAMBDA_FUNCTION_NAME: "testlambda"
    AWS_DEFAULT_REGION: "ap-southeast-2"
    S3_BUCKET_NAME: "triggerlambda301025"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Installing Node.js dependencies..."
      - npm install --production || true

  build:
    commands:
      - echo "🏗️ Build started..."
      - mkdir -p output
      - echo "📦 Creating Lambda deployment package..."
      - zip -r output/function.zip . -x "buildspec*" "*.git*" "*.md" "node_modules/.cache/*"

  post_build:
    commands:
      - echo "✅ Build completed on $(date)"
      - echo "☁️ Uploading package to S3..."
      - aws s3 cp output/function.zip s3://$S3_BUCKET_NAME/testlambda/function.zip
      - echo "🔍 Checking uploaded file..."
      - aws s3 ls s3://$S3_BUCKET_NAME/testlambda/
      - echo "🚀 Updating Lambda function code..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key testlambda/function.zip --publish
      - echo "🎉 Lambda function code updated successfully!"

artifacts:
  files:
    - output/function.zip
  discard-paths: yes
