version: 0.2

env:
  variables:
    LAMBDA_FUNCTION_NAME: "job_campaign_worker"
    AWS_DEFAULT_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing production dependencies..."
      - npm ci --omit=dev

  build:
    commands:
      - echo "Cleaning old package..."
      - rm -f function.zip

      - echo "Creating deployment package from root..."
      - zip -r function.zip index.js package.json package-lock.json node_modules

      - echo "Verify zip contents..."
      - unzip -l function.zip

  post_build:
    commands:
      - echo "Updating Lambda directly (no S3)..."
      - aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://function.zip --publish

      - echo "Deployment completed successfully!"
